### ISSUE TITLE
question about the get_distance function

### ISSUE THREAD

**Issue by qhxxsb** [kpandey008/carla-aebs#3]
Hi again,

I am reading your code now. It's very good code and pretty interesting. Would you mind telling me how the get_distance function work? Why the picture goes through the neural network and squeezes the results can compute the distance?

self.perception_lec(frame).squeeze().item() * 120

Many thanks for your help!

**Comment by kpandey008** [comment]
the get_distance() method uses the trained CNN to estimate the distance between the 2 cars (The scenario is described in the project readme). While training the CNN I down-scaled the groundtruth distance by a factor of 120, due to which during inference I need to re-scale it by 120. The squeeze() is a PyTorch function and you can refer to their docs for more info.

**Comment by qhxxsb** [comment]
> the get_distance() method uses the trained CNN to estimate the distance between the 2 cars (The scenario is described in the project readme). While training the CNN I down-scaled the groundtruth distance by a factor of 120, due to which during inference I need to re-scale it by 120. The squeeze() is a PyTorch function and you can refer to their docs for more info.

Understand! Many thanks for your reply!
Have a nice  day!
